### ISSUE TITLE
[BUG] error on trying to install

### ISSUE THREAD

**Issue by EdFenner** [schroef/Extra-Image-List#2] opened 2020-03-22 20:28 UTC
**OS:**
OSX

**ADDON:**
 - Version: [e.g.: Release date or Version]

**Describe the bug**
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'Extra-Image-List_v0'

**Comment by schroef** [comment] 2020-05-13 19:32
Thanks for reporting, got same error in this issue #1 
I just tried my build of 2.82 and it shows properly. Ill check it later tonight

**Comment by schroef** [comment] 2020-05-13 19:33
I see the issue, i had already fixed this but never updated this repo. Ill do that tonight

**Comment by schroef** [comment] 2020-05-13 21:02
Actually it is there, my mistake, it is in the dev branch and this should work fine. Thanks for reminding me, ill change this and make 2.8 version the master

https://github.com/schroef/Extra-Image-List/blob/bl280_dev/

**Comment by schroef** [comment] 2020-05-14 00:37
Master is now updated to 2.8 and should work fine up to 2.83. Let me know if you run into issues.

**Comment by EdFenner** [comment] 2020-05-14 00:51
Blender 2.82a - Still doesn’t work

**Comment by NicSTT** [comment] 2020-05-19 12:17
I can confirm it isn't working on 2.82a

**Comment by NicSTT** [comment] 2020-05-19 13:08
I also get the same issue in 2.83 Beta.

**Comment by schroef** [comment] 2020-05-20 19:25
Okay, what branch did you guys use? I guess my change didn't come through properly. I have merged the dev 2.8 branch in master and it should be updated.

I just tried master and works for me in both 2.82 and 2.83
though my versions arent up to date. Ill try to check newer builds and see whats going on. 

You still get that same error as from the initial post? You also made sure you replaced the addon properly?

```
Traceback (most recent call last):
File "/Applications/Blender.app/Contents/Resources/2.82/scripts/modules/addon_utils.py", line 351, in enable
mod = import(module_name)
ModuleNotFoundError: No module named 'Extra-Image-List_v0'
```

**Comment by NicSTT** [comment] 2020-05-20 19:59
I've deleted the zip file, re-downloaded, and reinstalled; I get the same error as you post above.
Im using 2.82a, and your version of the plugin is stated to be 0.2.3

**Comment by NicSTT** [comment] 2020-05-20 20:13
![error](https://user-images.githubusercontent.com/44039716/82492793-b4812080-9ade-11ea-8fb4-c96fad5c7dcd.jpg)

**Comment by schroef** [comment] 2020-05-20 20:23
Ah i see, i had same issue but it still shows for me on OSX. Its the issue with the dashes in the name. For me the addon still shows in the UV editor in the properties panel. I do see its name should be addressed
![Screen Shot 2020-05-20 at 16 23 52](https://user-images.githubusercontent.com/6923008/82493688-5c362880-9ab6-11ea-9e90-95e524cc2be5.png)


Could you try renaming the addon folder with underscores, so it looks like this
```
Extra_image_list
```

**Comment by schroef** [comment] 2020-05-20 20:27
Im not sure where that "_v0" comes from in you version. DId you change names to something different, is it in a copy of a folder with that name?

EDIT
Ah I see its from the zip you used. Try renaming the folder in the addon folder. It should work properly then

I can confirm its due to the dots I added in the zips. Ill try to address that tonight. For now removing that works fine on my side. So name should be ```Extra-Image-List```

**Comment by NicSTT** [comment] 2020-05-20 21:02
Didn't change anything
It allowed me to activate it when I renamed as you posted.
It appears to be working correctly, thank you.

**Comment by schroef** [comment] 2020-05-20 21:14
Thanks for confirming, sorry for the fuzz. It was my mistake by adding versioning numbers with dots to the zips.

**Closed as completed** 2020-05-25 16:02 UTC
Labels: bug
